# Generated by Django 2.2.16 on 2020-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限描述')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='vip种类')),
                ('level', models.IntegerField(verbose_name='会员等级')),
                ('duration', models.IntegerField(verbose_name='会员时长')),
                ('price', models.FloatField(verbose_name='会员价格')),
            ],
            options={
                'db_table': 'vip',
            },
        ),
        migrations.CreateModel(
            name='VipPermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_level', models.IntegerField(verbose_name='会员等级')),
                ('perm_id', models.IntegerField(verbose_name='权限id')),
            ],
            options={
                'db_table': 'vip_perm_relation',
            },
        ),
    ]
