# Generated by Django 2.2.16 on 2020-09-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='female', max_length=10, verbose_name='匹配性别')),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('沈阳', '沈阳'), ('西安', '西安'), ('武汉', '武汉')], default='上海', max_length=10, verbose_name='目标城市')),
                ('max_distance', models.FloatField(default=10, verbose_name='最大查找范围')),
                ('min_distance', models.FloatField(default=0, verbose_name='最小查找范围')),
                ('max_dating_age', models.IntegerField(default=60, verbose_name='最大交友年龄')),
                ('min_dating_age', models.IntegerField(default=15, verbose_name='最小交友年龄')),
                ('vibration', models.BooleanField(default=False, verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=False, verbose_name='运行查看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=20, verbose_name='昵称')),
                ('phonenum', models.CharField(max_length=16, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(default='2000-01-01', verbose_name='生日')),
                ('avatar', models.CharField(max_length=256, verbose_name='头像')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('沈阳', '沈阳'), ('西安', '西安'), ('武汉', '武汉')], default='上海', max_length=10, verbose_name='所在地')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
